### ISSUE TITLE
[Issue]: RPP Test Suite - HIP: Link error with OpenMP

### ISSUE THREAD

**Issue by kiritigowda** [ROCm/rpp#492]
### Problem Description

```
3: [ 75%] Linking CXX executable Tensor_misc_hip
3: ld.lld: error: undefined symbol: omp_register_coarse_grain_mem
3: >>> referenced by Tensor_misc_hip.cpp
3: >>>               CMakeFiles/Tensor_misc_hip.dir/Tensor_misc_hip.cpp.o:(_ovlh_hipHostMalloc(void**, unsigned long, unsigned int))
3: >>> referenced by Tensor_misc_hip.cpp
3: >>>               CMakeFiles/Tensor_misc_hip.dir/Tensor_misc_hip.cpp.o:(_ovlh_hipMalloc(void**, unsigned long))
3: clang++: error: linker command failed with exit code 1 (use -v to see invocation)
3: make[2]: *** [CMakeFiles/Tensor_misc_hip.dir/build.make:157: Tensor_misc_hip] Error 1
3: make[1]: *** [CMakeFiles/Makefile2:111: CMakeFiles/Tensor_misc_hip.dir/all] Error 2
3: make[1]: *** Waiting for unfinished jobs....
3: [100%] Linking CXX executable Tensor_hip
3: ld.lld: error: undefined symbol: omp_register_coarse_grain_mem
3: >>> referenced by Tensor_hip.cpp
3: >>>               CMakeFiles/Tensor_hip.dir/Tensor_hip.cpp.o:(_ovlh_hipHostMalloc(void**, unsigned long, unsigned int))
3: >>> referenced by Tensor_hip.cpp
3: >>>               CMakeFiles/Tensor_hip.dir/Tensor_hip.cpp.o:(_ovlh_hipMalloc(void**, unsigned long))
3: clang++: error: linker command failed with exit code 1 (use -v to see invocation)
3: make[2]: *** [CMakeFiles/Tensor_hip.dir/build.make:157: Tensor_hip] Error 1
3: make[1]: *** [CMakeFiles/Makefile2:85: CMakeFiles/Tensor_hip.dir/all] Error 2
3: make: *** [Makefile:91: all] Error 2
3: 
3: 
3: ./Tensor_hip /opt/rocm-6.4.0/share/rpp/test/HIP/../TEST_IMAGES/three_images_mixed_src1 /opt/rocm-6.4.0/share/rpp/test/HIP/../TEST_IMAGES/three_images_mixed_src2 /root/test/QA_RESULTS_HIP_2024-12-20_20-03-05 0 0 0 0 1 0 0
3: Traceback (most recent call last):
3:   File "/opt/rocm/share/rpp/test/HIP/runTests.py", line 307, in <module>
3:     run_unit_test(srcPath1, srcPath2, dstPathTemp, case, numRuns, testType, layout, qaMode, decoderType, batchSize, roiList)
3:   File "/opt/rocm/share/rpp/test/HIP/runTests.py", line 91, in run_unit_test
3:     result = subprocess.Popen([buildFolderPath + "/build/Tensor_hip", srcPath1, srcPath2, dstPathTemp, str(bitDepth), str(outputFormatToggle), str(case), "0", str(numRuns), str(testType), str(layout), "0", str(qaMode), str(decoderType), str(batchSize)] + roiList + [scriptPath], stdout=subprocess.PIPE, stderr=subprocess.PIPE)    # nosec
3:   File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
3:     self._execute_child(args, executable, preexec_fn, close_fds,
3:   File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
3:     raise child_exception_type(errno_num, err_msg, err_filename)
3: FileNotFoundError: [Errno 2] No such file or directory: '/root/test/build/Tensor_hip'
1/1 Test #3: rpp_qa_tests_tensor_hip_all ......***Failed   18.20 sec
```

### Operating System

ALL

### CPU

ALL

### GPU

AMD Instinct MI300

### ROCm Version

ROCm 6.0.0

### ROCm Component

rpp

### Steps to Reproduce

Latest Mainline failures

**Comment by kiritigowda** [comment]
OpenMP definition found
```
grep -ir "omp_register_coarse_grain_mem" /opt/rocm/
grep: /opt/rocm/lib/llvm/lib/libomptarget.so.19.0git: binary file matches
/opt/rocm/lib/llvm/lib/clang/19/include/openmp_wrappers/hip_host_overlay.h:  omp_register_coarse_grain_mem(*p, sz, /*set_attr*/ 0);
/opt/rocm/lib/llvm/lib/clang/19/include/openmp_wrappers/hip_host_overlay.h:  omp_register_coarse_grain_mem(*p, sz, /*set_attr*/ 0);
/opt/rocm/lib/llvm/include/omp.h:    extern void  __KAI_KMPC_CONVENTION  omp_register_coarse_grain_mem(void *, size_t, int);
grep: /opt/rocm/lib/llvm/lib-debug/libomptarget.so.19.0git: binary file matches
/opt/rocm/lib/llvm/lib-debug/src/offload/src/exports:    omp_register_coarse_grain_mem;
/opt/rocm/lib/llvm/lib-debug/src/offload/src/OpenMP/API.cpp:EXTERN void omp_register_coarse_grain_mem(void *ptr, size_t size, int setattr) {
/opt/rocm/lib/llvm/lib-debug/src/openmp/runtime/src/dllexports:	omp_register_coarse_grain_mem       902
/opt/rocm/lib/llvm/lib-debug/src/openmp/runtime/src/include/omp.h.var:    extern void  __KAI_KMPC_CONVENTION  omp_register_coarse_grain_mem(void *, size_t, int);

```

**Comment by kiritigowda** [comment]
Definition missing in old

```
grep -ir "omp_register_coarse_grain_mem" /opt/rocm/
kiriti@simoncat:~/develop/rpp-kiriti/test$ dpkg -l | grep rocm-core
ii  rocm-core                                  6.4.0.60400-crdnnh.15028~22.04          amd64        Radeon Open Compute (ROCm) Runtime software stack
```

**Comment by kiritigowda** [comment]
def found in 

```
nm /opt/rocm/lib/llvm/lib-debug/libomptarget.so | grep omp_register_coarse_grain_mem
00000000017f2f20 T omp_register_coarse_grain_mem
```

**Comment by kiritigowda** [comment]
Explicitly adding this lib - libomptarget.so

```
3: CMake Warning at CMakeLists.txt:194 (add_executable):
3:   Cannot generate a safe runtime search path for target Tensor_hip because
3:   there is a cycle in the constraint graph:
3: 
3:     dir 0 is [/opt/rocm/lib]
3:     dir 1 is [/usr/local/lib]
3:     dir 2 is [/opt/rocm/lib/llvm/lib]
3:       dir 3 must precede it due to runtime library [libomptarget.so.19.0git]
3:     dir 3 is [/opt/rocm/lib/llvm/lib-debug]
3:       dir 4 must precede it due to runtime library [libomp.so]
3:     dir 4 is [/opt/rocm-6.4.0/lib/llvm/lib]
3:       dir 3 must precede it due to runtime library [libomptarget.so.19.0git]
3: 
3:   Some of these libraries may not be found correctly.
3: 
3: 
3: CMake Warning at CMakeLists.txt:249 (add_executable):
3:   Cannot generate a safe runtime search path for target Tensor_misc_hip
3:   because there is a cycle in the constraint graph:
3: 
3:     dir 0 is [/opt/rocm/lib]
3:     dir 1 is [/usr/local/lib]
3:     dir 2 is [/opt/rocm/lib/llvm/lib]
3:       dir 3 must precede it due to runtime library [libomptarget.so.19.0git]
3:     dir 3 is [/opt/rocm/lib/llvm/lib-debug]
3:       dir 4 must precede it due to runtime library [libomp.so]
3:     dir 4 is [/opt/rocm-6.4.0/lib/llvm/lib]
3:       dir 3 must precede it due to runtime library [libomptarget.so.19.0git]
3: 
3:   Some of these libraries may not be found correctly.
3: 
3: 
3: -- Generating done
3: -- Build files have been written to: /root/test/build
3: [ 25%] Building CXX object CMakeFiles/Tensor_hip.dir/Tensor_hip.cpp.o
3: [ 50%] Building CXX object CMakeFiles/Tensor_misc_hip.dir/Tensor_misc_hip.cpp.o
3: [ 75%] Linking CXX executable Tensor_misc_hip
3: [ 75%] Built target Tensor_misc_hip
3: [100%] Linking CXX executable Tensor_hip
3: [100%] Built target Tensor_hip
```

**Comment by kiritigowda** [comment]
Issue not seen in the ROCm public releases

**Comment by kiritigowda** [comment]
Passing on #15463

```
root@simoncat:~/test# ctest    
Test project /root/test
    Start 1: rpp_qa_tests_tensor_image_host_all
1/8 Test #1: rpp_qa_tests_tensor_image_host_all ...   Passed  123.02 sec
    Start 2: rpp_qa_tests_tensor_voxel_host_all
2/8 Test #2: rpp_qa_tests_tensor_voxel_host_all ...   Passed   20.54 sec
    Start 3: rpp_qa_tests_tensor_audio_host_all
3/8 Test #3: rpp_qa_tests_tensor_audio_host_all ...   Passed   10.67 sec
    Start 4: rpp_qa_tests_tensor_misc_host_all
4/8 Test #4: rpp_qa_tests_tensor_misc_host_all ....   Passed   10.21 sec
    Start 5: rpp_qa_tests_tensor_image_hip_all
5/8 Test #5: rpp_qa_tests_tensor_image_hip_all ....   Passed  229.18 sec
    Start 6: rpp_qa_tests_tensor_voxel_hip_all
6/8 Test #6: rpp_qa_tests_tensor_voxel_hip_all ....   Passed   41.08 sec
    Start 7: rpp_qa_tests_tensor_audio_hip_all
7/8 Test #7: rpp_qa_tests_tensor_audio_hip_all ....   Passed   27.46 sec
    Start 8: rpp_qa_tests_tensor_misc_hip_all
8/8 Test #8: rpp_qa_tests_tensor_misc_hip_all .....   Passed   25.26 sec

100% tests passed, 0 tests failed out of 8

Total Test time (real) = 487.42 sec
root@simoncat:~/test# dpkg -l | grep rocm-core
ii  rocm-core                            6.4.0.60400-crdnnh.15463~24.04        amd64        Radeon Open Compute (ROCm) Runtime software stack
```
